version: '3.4'

services:

#Registry
  registry:
    image: registry:2
    restart: always
    ports:
    - "5000:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
    volumes:
      - /root/docker_registry/data:/var/lib/registry
      - /root/docker_registry/auth:/auth
      - /root/docker_registry/certs:/certs
    networks:
      - registry-net

    
#Docker Networks
networks:
  registry-net:
    driver: bridge
