version: '3.4'

services:
  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3-management-alpine"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "USERNAME"
      RABBITMQ_DEFAULT_PASS: "PASSWORD"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - 15672:15672
      - 5672:5672
    labels:
      NAME: "rabbitmq"
    volumes:
        - /var/docker_volumes/rabbitmq/data/:/var/lib/rabbitmq/
        - /var/docker_volumes/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - my-network
    restart: always

networks:
  my-network: 
    external: true