version: '3.8'

networks:
  web-net:
    external: true

services:

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/docker_volumes/gitlab-runner/config:/etc/gitlab-runner
    networks:
      - web-net

  register-gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    volumes:
      - /var/docker_volumes/gitlab-runner/config:/etc/gitlab-runner
    command:
      - register
      - --non-interactive
      - --locked=false
      - --run-untagged
      - --name=GitLab Runner
      - --tag-list=dev
      - --executor=docker
      - --privileged=true
      - --docker-image=docker:stable
      - --docker-volumes=/var/run/docker.sock:/var/run/docker.sock
      - --docker-network-mode=web-net
    environment:
      - "CI_SERVER_URL=http://${DOMAIN?domain variable is not set}"
      - "REGISTRATION_TOKEN=${GITLAB_TOKEN?token variable is not set}"
    networks:
      - web-net
