version: "3.3"
services:
#Registry
  registery:
    image: registry:2
    restart: always
    container_name: registery
    ports:
    - "5000:5000"
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
    volumes:
      - /root/docker_data/image:/var/lib/registry
      - /root/docker_data/certs:/certs
    networks:
      - mynet
    
  registry_ui:
    image: konradkleine/docker-registry-frontend:v2
    container_name: registery_ui
    ports:
      - 8888:80
    env_file:
      - .env
    depends_on:
      - nexus
    environment:
      ENV_DOCKER_REGISTRY_HOST: registery
      ENV_DOCKER_REGISTRY_PORT: 5000
    restart: always

networks:
  mynet:
    driver: bridge
#Volumes
volumes:
  registrydata:
    driver: local