version: '3.7'

volumes:
   pgdb:

services:
  redis:
    image: redis
    restart: always
    networks:
      - sentry

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: sentry
      POSTGRES_PASSWORD: sentry
      POSTGRES_DB: sentry
    volumes:
     - pgdb:/var/lib/postgresql/data
    networks:
      - sentry

  sentry:
    image: sentry
    restart: always
    links:
     - redis
     - postgres
    ports:
     - 9000:9000
    environment:
      SENTRY_SECRET_KEY: 'ASDfion3209f2n3fiwnf232!$23rs'
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_REDIS_HOST: redis
    networks:
      - sentry

  cron:
    image: sentry
    restart: always
    links:
     - redis
     - postgres
    command: "sentry run cron"
    environment:
      SENTRY_SECRET_KEY: 'ASDfion3209f2n3fiwnf232!$23rs'
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_REDIS_HOST: redis
    networks:
      - sentry

  worker:
    image: sentry
    restart: always
    links:
     - redis
     - postgres
    command: "sentry run worker"
    environment:
      SENTRY_SECRET_KEY: 'ASDfion3209f2n3fiwnf232!$23rs'
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_REDIS_HOST: redis
    networks:
      - sentry


networks:
  sentry:
    driver: bridge