version: '3.4'

services:

  sentry:
    container_name: sentry
    image: sentry
    env_file:
      - .env
    ports:
      - '9000:9000'
    depends_on:
      - db
      - redis
    tty: true
    networks:
      - sentry
    stdin_open: true

  cron:
    container_name: sentry-cron
    image: sentry
    command: run cron
    env_file:
      - .env
    networks:
      - sentry
    depends_on:
      - db
      - redis

  worker:
    container_name: sentry-worker
    image: sentry
    command: run worker
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - sentry

  redis:
    container_name: sentry-redis
    image: redis
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'
    networks:
      - sentry

  db:
    container_name: sentry-postgres
    image: postgres
    environment:
      POSTGRES_USER: sentry
      POSTGRES_PASSWORD: secret_password_formeandyou
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - sentry

volumes:
  redis-data:
  pg-data:

networks:
  sentry: 
    external: true