version: '3.8'

networks:
  app-net:
    driver: overlay

services:
  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.name == {name}
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "USERNAME"
      RABBITMQ_DEFAULT_PASS: "PASSWORD"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - 15672:15672
      - 5672:5672
    labels:
      NAME: "rabbitmq"
    volumes:
        - /var/docker_volumes/rabbitmq/data/:/var/lib/rabbitmq/
        - /var/docker_volumes/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - app-net
