version: "3.4"

services:
  nexus:
    build: sonatype/nexus3
    ports:
      - "8082:8081"
      - "5000:5000"
    volumes:
      - "/var/docker_volumes/nexus:/nexus-data"
    container_name: nexus
    restart: always
