version: "3.8"

volumes:
  traefik-acme:
    name: traefik-acme

networks:
  web-net:
    external: true

services:
  traefik:
    image: traefik:2.6.1
    container_name: c_traefik
    command:
      - --log.level=INFO
      - --log.filepath=/log-file.log
      - --log.format=json
      - --api=true
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=web-net
      - --ping=true
      - --accesslog=true
      - --accesslog.bufferingsize=100
      - --certificatesresolvers.mycert.acme.storage=/acme/acme.json
      - --certificatesresolvers.mycert.acme.tlschallenge=true
      - --providers.file.filename=/conf/config.yml
      - --providers.docker.constraints=Label(`traefik.constraint-label`, `web-net`)
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --certificatesresolvers.mycert.acme.email=${EMAIL?email variable not set}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web_net"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`${DOMAIN?Traefik domain variable not set}`)"
      - "traefik.http.routers.traefik.middlewares=https-redirect"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.web-auth.basicauth.users=${USERNAME?Username variable not set}:${HASHED_PASSWORD?hashed_password variable not set}"
      - "traefik.http.routers.traefik-secure.middlewares=web-auth"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`${DOMAIN?Traefik domain variable not set}`)"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.options=default"
      - "traefik.http.routers.traefik-secure.tls.certresolver=mycert"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    ports:
      - 80:80
      - 443:443

    volumes:
      - ./conf/traefik.yml:/etc/traefik/traefik.yml
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-acme:/acme
      - ./var/docker_volumes/traefik:/traefik
    networks:
      # Use the public network created to be shared between Traefik and any other service that needs to be publicly available with HTTPS
      - web-net
