version: '3'

services:
  postgre_atlassian:
    image: blacklabelops/postgres
    container_name: postgre_atlassian
    hostname: postgre_atlassian
    restart: unless-stopped
    networks:
      - atlassiannet
    volumes:
      - /var/docker_volumes/postgre_atlassian/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=QksuYejx_speI93'
      - 'POSTGRES_ENCODING=UNICODE'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
    labels:
      com.blacklabelops.description: "Postgre Atlassian Database Server"
      com.blacklabelops.service: "postgre_atlassian"

  jira:
    depends_on:
      - postgre_atlassian
    image: blacklabelops/jira
    container_name: jira
    hostname: jira
    restart: unless-stopped
    networks:
      - atlassiannet
    volumes:
      - jiradata:/var/atlassian/jira
    ports:
      - '8085:8080'
    environment:
      - 'JIRA_DATABASE_URL=postgresql://postgres:QksuYejx_speI93@postgre_atlassian/jiradb'
      - 'JIRA_DB_PASSWORD=Jiaia921843kfaHWy'
      - 'CATALINA_OPTS= -Xms2g -Xmx3g'
      - 'JVM_MINIMUM_MEMORY=2g'
      - 'JVM_MAXIMUM_MEMORY=3g'
      - 'JIRA_PROXY_NAME='
      - 'JIRA_PROXY_PORT='
      - 'JIRA_PROXY_SCHEME='
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
    labels:
      com.blacklabelops.description: "Atlassian Jira"
      com.blacklabelops.service: "jira"

networks:
  atlassiannet:
    external:
      name: network-atlassian

volumes:
  jiradata:
    external: true
