version: '3.4'

services:
  elasticsearch:
    image: elasticsearch:7.15.1
    container_name: elasticsearch
    environment:
      - node.name=es
      - cluster.name=es-docker
      - cluster.initial_master_nodes=es
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms3G -Xmx3G"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /var/docker_volumes/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

networks:
  elastic:
    external: true
