version: '3.4'

services:
  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
      - 6379:6379
    labels:
      NAME: "redis"
    networks:
      - my-network

networks:
  my-network: 
    external: true